# This is a basic workflow to help you get started with Actions

name: Deploy database to Azure Database for PostgreSQL

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.58.1
      
      - name: Download Adventureworks data file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorks-oltp-install-script.zip
     
      - name: Unzip Adventureworks data file
        uses: montudor/action-zip@v0.1.1
        with:
          # See montudor/action-zip README.md for more info
          args: unzip -qq AdventureWorks-oltp-install-script.zip -d .
   
      - name: Prep Adventurework files for Postgres insertion
        run: ruby update_csvs.rb
     
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      - name: Azure PostgreSQL Action
        uses: Azure/postgresql@v1
        with:
          # Server name of Azure DB for PostgreSQL. Example: fabrikam.postgres.database.azure.com
          server-name: wollongongpgsql01
          # The connection string, including authentication information, for the Azure PostgreSQL Server. Please provide psql connection string. Example: psql "host={host} port={port} dbname={your_database} user={user} password={your_password} sslmode=require"
          connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
          # Path to PL/SQL script file to deploy. To specify multiple files, use the regex syntax : *.sql or folder/x/<regex>.sql
          plsql-file: ./install.sql
